# Generated by Django 4.1.7 on 2023-03-21 02:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id_cam', models.AutoField(primary_key=True, serialize=False)),
                ('name_cam', models.CharField(max_length=100)),
                ('name_location', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id_detect', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name_detect', models.CharField(max_length=100)),
                ('name_cam', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image_detect', models.ImageField(default='bienbao.png', upload_to='detect_image')),
                ('time_detect', models.CharField(max_length=100)),
            ],
        ),
    ]
