# Generated by Django 4.1.7 on 2023-03-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canhbao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='port',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
