# Generated by Django 4.1.7 on 2023-03-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canhbao', '0002_camera_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='port',
            field=models.IntegerField(default=2222),
        ),
    ]
