# Generated by Django 4.1.7 on 2023-04-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canhbao", "0004_customuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="latitude",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="camera",
            name="longitude",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
