# Generated by Django 4.1.7 on 2023-04-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canhbao", "0005_camera_latitude_camera_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="detection",
            name="id_cam",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
